export const RATING_SUBMIT_REQUEST = "RATING_SUBMIT_REQUEST";
export const RATING_SUBMIT_SUCCESS = "RATING_SUBMIT_SUCCESS";
export const RATING_SUBMIT_FAILURE = "RATING_SUBMIT_FAILURE";

export const RATING_RESET = "RATING_RESET";
