export const FETCH_INTERESTS_REQUEST = "FETCH_INTERESTS_REQUEST";
export const FETCH_INTERESTS_SUCCESS = "FETCH_INTERESTS_SUCCESS";
export const FETCH_INTERESTS_FAILURE = "FETCH_INTERESTS_FAILURE";


export const SELECT_INTERESTS_REQUEST = "SELECT_INTERESTS_REQUEST";
export const SELECT_INTERESTS_SUCCESS = "SELECT_INTERESTS_SUCCESS";
export const SELECT_INTERESTS_FAILURE = "SELECT_INTERESTS_FAILURE";
